name: Docker

on:
  push:
    branches: [ main ]
    tags:
      - v*

jobs:
  docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: bspaulding/sixty-three
        tag_with_ref: true


