name: Elm CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install create-elm-app
      run: npm i -g create-elm-app
    - name: Run tests
      run: cd frontend && elm-app test

