name: Elm CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        path: frontend/node_modules
        key: create-elm-app-1
    - name: Install create-elm-app
      run: cd frontend && npm i create-elm-app
    - name: Run tests
      run: cd frontend && ./node_modules/.bin/elm-app test
