name: Elm CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Cache
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: create-elm-app-2
    - name: Install create-elm-app
      run: cd frontend && npm ci
    - name: Run tests
      run: cd frontend && npm run elm-app -- test
